# This workflow is designed to build PRs for AHC. Note that it does not actually publish AHC, just builds and test it.
# Docs: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# SolarMC: Changed this to publish AHC to our repo
name: Java CI

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn clean -B -U verify -Ptest-output
  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/solar'
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          server-id: solar-repo
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build with Maven
        run: mvn clean -B -U deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CD_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CD_PASS }}

